// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ61nnIY5fObz0mb2aXrANuLYXJLMenio',
    appId: '1:157177702220:web:5a0d1026fe56eb42e7d1e9',
    messagingSenderId: '157177702220',
    projectId: 'chaty-162b5',
    authDomain: 'chaty-162b5.firebaseapp.com',
    storageBucket: 'chaty-162b5.firebasestorage.app',
    measurementId: 'G-58R1PEG808',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1zMZu-uwyIXqFW0b-G8FBI80xeK2WE90',
    appId: '1:157177702220:android:809f8598153771a4e7d1e9',
    messagingSenderId: '157177702220',
    projectId: 'chaty-162b5',
    storageBucket: 'chaty-162b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmB-gw1C_UJ8-v_sgS7EHWAeeiye_LS6Y',
    appId: '1:157177702220:ios:cb337cf31b80575ae7d1e9',
    messagingSenderId: '157177702220',
    projectId: 'chaty-162b5',
    storageBucket: 'chaty-162b5.firebasestorage.app',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmB-gw1C_UJ8-v_sgS7EHWAeeiye_LS6Y',
    appId: '1:157177702220:ios:cb337cf31b80575ae7d1e9',
    messagingSenderId: '157177702220',
    projectId: 'chaty-162b5',
    storageBucket: 'chaty-162b5.firebasestorage.app',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ61nnIY5fObz0mb2aXrANuLYXJLMenio',
    appId: '1:157177702220:web:942390b1bd78c144e7d1e9',
    messagingSenderId: '157177702220',
    projectId: 'chaty-162b5',
    authDomain: 'chaty-162b5.firebaseapp.com',
    storageBucket: 'chaty-162b5.firebasestorage.app',
    measurementId: 'G-97NKXLLG5T',
  );
}
